Cloud SQL 26
java.lang.InstantiationException: Type `com.google.api.services.sqladmin.model.AclEntry` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.