Cloud SQL 15
java.lang.RuntimeException: [slalom-2020-293920:us-central1:upgraded-garbanzo] Failed to update metadata for Cloud SQL instance.

GET https://www.googleapis.com/sql/v1beta4/projects//instances/ -> 400
Invalid request: Missing parameter: Project ID.