Cloud SQL 25
java.lang.InstantiationException: Type `com.google.api.services.sqladmin.model.Settings` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.

java.lang.RuntimeException: [slalom-2020-293920:us-central1:upgraded-garbanzo] Failed to create ephemeral certificate for the Cloud SQL instance.
	at com.google.cloud.sql.core.CloudSqlInstance.addExceptionContext(CloudSqlInstance.java:481)
	at com.google.cloud.sql.core.CloudSqlInstance.fetchEphemeralCertificate(CloudSqlInstance.java:341)